version: '3.8'

services:
  db:
    environment:
      POSTGRES_DB: db_app
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    restart: always
    image: postgres:15.5-alpine
    ports:
      - "5433:5432"
    networks:
      - clock-network

      
      
  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.web
    ports:
      - "8030:8000"
      - "4444:4444"
    volumes:
      - .:/app
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://db_user:db_pass@db:5432/db_app
      - JWT_PUBLIC_KEY_PATH=./certs/public.pem
      - JWT_ALGORITHM=RS256
      - SMTP_SERVER=mailhog
      - SMTP_PORT=1025
      - SMTP_TLS=false
      - SMTP_USER=
      - SMTP_PASSWORD=
      - SIGNATURE_SECRET_KEY=secret
      - CLERK_LIST=http://hr-login-web:8000/users/clerks
    depends_on:
      - db 
      - mailhog
    networks:
      - clock-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - clock-network

networks:
  clock-network:
    name: clock-network
    external: true





