[tool.poetry]
name = "api"
version = "1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115.8"
uvicorn = "^0.34.0"
pydantic-settings = "^2.7.1"
sqlalchemy = "^2.0.38"
psycopg2-binary = "^2.9.10"
pyjwt = {extras = ["crypto"], version = "^2.10.1"}
alembic = "^1.14.1"
sqlmodel = "^0.0.22"
pytest = "^8.3.5"
httpx = "^0.28.1"
python-multipart = "^0.0.20"
websockets = "^15.0.1"
pydantic = {extras = ["email"], version = "^2.11.4"}
pikepdf = "^9.11.0"
requests = "^2.32.5"
sqladmin = "^0.22.0"
itsdangerous = "^2.2.0"
freezegun = "^1.5.5"
isort = "^8.0.1"
black = "^26.5.1"

[tool.black]
exclude = '''
/(migrations)/
| /venv
'''
line_length = 88
target_version = ["py313"]

[tool.isort]
profile = "black"
py_version = 313
multi_line_output = 3
line_length = 88


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
