[tool.poetry]
name = "cloclwork-backend"
version = "1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115.8"
uvicorn = "^0.34.0"
pydantic-settings = "^2.7.1"
sqlalchemy = "^2.0.38"
psycopg2-binary = "^2.9.10"
pyjwt = "^2.10.1"
alembic = "^1.14.1"
sqlmodel = "^0.0.22"
pytest = "^8.3.5"
httpx = "^0.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
