"""create employee table and add user as foriegn key

Revision ID: 0101eb42e716
Revises: c5f71e650057
Create Date: 2025-03-18 01:19:34.080285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '0101eb42e716'
down_revision: Union[str, None] = 'c5f71e650057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_account', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('form_of_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('city_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('married', sa.Boolean(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telephone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health_insurance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('previous_employment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prev_emp_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iban', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('petition', 'user_account',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='user_account::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('petition', 'user_account',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='user_account::text')
    op.drop_table('employee')
    # ### end Alembic commands ###
