"""Create prev_employment

Revision ID: 06d7685e2d3c
Revises: 54a1dd4c2bd8
Create Date: 2026-08-31 09:05:57.018068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '06d7685e2d3c'
down_revision: Union[str, None] = '54a1dd4c2bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prevemployment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_account', sa.Uuid(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('employer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proof', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prevemployment')
    # ### end Alembic commands ###
