"""rename_previously_employed

Revision ID: 1e6230378f1e
Revises: 76b6eb43b5c0
Create Date: 2025-12-13 00:34:34.362067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '1e6230378f1e'
down_revision: Union[str, None] = '76b6eb43b5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('previously_employed', sa.Boolean(), nullable=True))
    op.drop_column('employee', 'previously_employeed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('previously_employeed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('employee', 'previously_employed')
    # ### end Alembic commands ###
