"""empty message

Revision ID: 23a987f7b321
Revises: 94b645356315
Create Date: 2025-11-29 20:31:02.286217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '23a987f7b321'
down_revision: Union[str, None] = '94b645356315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('employee', 'user_email')
    op.add_column('petition', sa.Column('student_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('petition', 'student_mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('student_mail', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('petition', 'student_username')
    op.add_column('employee', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employee', 'username')
    # ### end Alembic commands ###
