"""create one to many relation for budget and petition

Revision ID: 2c3269655e8b
Revises: 5154cba6ce5b
Create Date: 2025-07-30 21:39:31.184769

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c3269655e8b'
down_revision: Union[str, None] = '5154cba6ce5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petition', 'budget_approver')
    op.drop_column('petition', 'budget_approved')
    op.drop_column('petition', 'budget_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('budget_position', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('petition', sa.Column('budget_approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('petition', sa.Column('budget_approver', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
