"""budget table and its relation with petition

Revision ID: 3578325f322b
Revises: 2c3269655e8b
Create Date: 2025-07-30 22:36:19.145625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '3578325f322b'
down_revision: Union[str, None] = '2c3269655e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgetposition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('petition_id', sa.Uuid(), nullable=False),
    sa.Column('budget_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_approver', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budgetposition')
    # ### end Alembic commands ###
