"""empty message

Revision ID: 3d2e4d2bf81b
Revises: 23a987f7b321
Create Date: 2025-12-01 10:36:51.243367

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d2e4d2bf81b'
down_revision: Union[str, None] = '23a987f7b321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('time_exce_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petition', 'time_exce_time')
    # ### end Alembic commands ###
