"""add useremail field to employee table

Revision ID: 4d00be87e03e
Revises: 7db3c962c497
Create Date: 2025-04-23 17:30:02.833892

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d00be87e03e'
down_revision: Union[str, None] = '7db3c962c497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'user_email')
    # ### end Alembic commands ###
