"""resolve the issue of wrong relation allocation in models

Revision ID: 51535a85ed9a
Revises: 8d63153b5241
Create Date: 2025-04-10 14:49:07.815260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '51535a85ed9a'
down_revision: Union[str, None] = '8d63153b5241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentdocuments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('elstam_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('studienbescheinigung_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('versicherungsbescheinigung_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentdocuments')
    # ### end Alembic commands ###
