"""Use GenderEnum

Revision ID: 54a1dd4c2bd8
Revises: 916146966fdf
Create Date: 2026-08-28 05:00:56.480407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '54a1dd4c2bd8'
down_revision: Union[str, None] = '916146966fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

gender_enum = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender', create_type=False)


def upgrade() -> None:
    gender_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        'employee', 'gender',
        existing_type=sa.VARCHAR(),
        type_=gender_enum,
        postgresql_using='gender::gender',
        existing_nullable=True,
    )
    op.drop_column('petition', 'time_exce_end')
    op.drop_column('petition', 'time_exce_start')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('time_exce_start', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('petition', sa.Column('time_exce_end', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column(
        'employee', 'gender',
        existing_type=gender_enum,
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    gender_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
