"""update the table of documents to make id field not null

Revision ID: 5ca4def95290
Revises: 6e0ea8793cdc
Create Date: 2025-04-12 14:17:31.426369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '5ca4def95290'
down_revision: Union[str, None] = '6e0ea8793cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
