"""update the table of employee to make all fields optional

Revision ID: 6e0ea8793cdc
Revises: 51535a85ed9a
Create Date: 2025-04-10 20:25:52.284167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '6e0ea8793cdc'
down_revision: Union[str, None] = '51535a85ed9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'form_of_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employee', 'city_of_birth',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'married',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('employee', 'nationality',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'telephone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'health_insurance',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'iban',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'iban',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'health_insurance',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'telephone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'nationality',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'married',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('employee', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'city_of_birth',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employee', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'form_of_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
