"""add the field of supervisor email in petition

Revision ID: 7db3c962c497
Revises: 5ca4def95290
Create Date: 2025-04-23 16:28:05.433487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '7db3c962c497'
down_revision: Union[str, None] = '5ca4def95290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('supervisor_mail', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petition', 'supervisor_mail')
    # ### end Alembic commands ###
