"""

Revision ID: 92d7693e8b03
Revises: 8429065d4bd0
Create Date: 2025-09-24 13:01:35.304471

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '92d7693e8b03'
down_revision: Union[str, None] = '8429065d4bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('previously_employeed', sa.Boolean(), nullable=True))
    op.drop_column('employee', 'previous_employment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('previous_employment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employee', 'previously_employeed')
    # ### end Alembic commands ###
