"""empty message

Revision ID: 94b645356315
Revises: 92d7693e8b03
Create Date: 2025-11-29 19:57:10.243230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '94b645356315'
down_revision: Union[str, None] = '92d7693e8b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentdocuments', sa.Column('sozialversicherungsbogen_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentdocuments', 'sozialversicherungsbogen_url')
    # ### end Alembic commands ###
