"""Create petition table

Revision ID: c5f71e650057
Revises: 
Create Date: 2025-02-24 22:50:45.582243

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5f71e650057'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eos_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('ba_degree', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_approver', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_mail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_exce_student', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_exce_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_exce_start', sa.Date(), nullable=True),
    sa.Column('time_exce_end', sa.Date(), nullable=True),
    sa.Column('duration_exce_student', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_exce_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_exce_start', sa.Date(), nullable=True),
    sa.Column('duration_exce_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petition')
    # ### end Alembic commands ###
