"""add unique constraint student documents

Revision ID: d360f7034b07
Revises: f47ac5282245
Create Date: 2025-12-24 16:10:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd360f7034b07'
down_revision: Union[str, None] = 'f47ac5282245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Clean up duplicate documents before adding constraint
    op.execute("""
        DELETE FROM studentdocuments
        WHERE id IN (
            SELECT id
            FROM (
                SELECT id,
                ROW_NUMBER() OVER (partition BY employee_id ORDER BY id) AS row_num
                FROM studentdocuments
            ) t
            WHERE t.row_num > 1
        );
    """)
    
    # Drop constraint if exists for idempotency
    op.execute("ALTER TABLE studentdocuments DROP CONSTRAINT IF EXISTS uq_studentdocuments_employee_id")
    
    op.create_unique_constraint('uq_studentdocuments_employee_id', 'studentdocuments', ['employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_studentdocuments_employee_id', 'studentdocuments', type_='unique')
    # ### end Alembic commands ###
