"""

Revision ID: db0f0147effd
Revises: 1e6230378f1e
Create Date: 2025-12-20 18:38:22.652648

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'db0f0147effd'
down_revision: Union[str, None] = '1e6230378f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentdocuments', sa.Column('ba_degree_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentdocuments', 'ba_degree_url')
    # ### end Alembic commands ###
