"""add percentage field in budget postion

Revision ID: e5a42cbf103d
Revises: 3578325f322b
Create Date: 2025-08-08 17:27:51.102242

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e5a42cbf103d'
down_revision: Union[str, None] = '3578325f322b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgetposition', sa.Column('percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgetposition', 'percentage')
    # ### end Alembic commands ###
