"""add duration exception for student whish field.

Revision ID: e65a0adeb339
Revises: 391a0c89e5c7
Create Date: 2026-08-13 18:46:52.090385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'e65a0adeb339'
down_revision: Union[str, None] = '391a0c89e5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'previously_employed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('employee', 'bic')
    op.drop_column('employee', 'bank_name')
    op.add_column('petition', sa.Column('duration_exec_student', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petition', 'duration_exec_student')
    op.add_column('employee', sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('bic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('employee', 'previously_employed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
