"""add a new field named as budget_position_status instead of budget approved which was a bool

Revision ID: ea22b8ac0713
Revises: e5a42cbf103d
Create Date: 2025-08-20 20:27:23.096492

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea22b8ac0713'
down_revision: Union[str, None] = 'e5a42cbf103d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgetposition', sa.Column('budget_position_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('budgetposition', 'budget_approved')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgetposition', sa.Column('budget_approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('budgetposition', 'budget_position_status')
    # ### end Alembic commands ###
