"""Add residence_permit and id_photo to student_documents

Revision ID: f3bf786cf92e
Revises: d360f7034b07
Create Date: 2026-03-01 13:48:55.395679

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3bf786cf92e'
down_revision: Union[str, None] = 'd360f7034b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentdocuments', sa.Column('residence_permit_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('studentdocuments', sa.Column('id_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentdocuments', 'id_photo_url')
    op.drop_column('studentdocuments', 'residence_permit_url')
    # ### end Alembic commands ###
