"""create petition timeline table

Revision ID: f3c895c0c105
Revises: d360f7034b07
Create Date: 2026-03-02 10:56:17.867914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'f3c895c0c105'
down_revision: Union[str, None] = 'd360f7034b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petitiontimeline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('petition_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_petitiontimeline_last_updated_at'), 'petitiontimeline', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_petitiontimeline_petition_id'), 'petitiontimeline', ['petition_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_petitiontimeline_petition_id'), table_name='petitiontimeline')
    op.drop_index(op.f('ix_petitiontimeline_last_updated_at'), table_name='petitiontimeline')
    op.drop_table('petitiontimeline')
    # ### end Alembic commands ###
