"""add unique constraint employee

Revision ID: f47ac5282245
Revises: 6f3f15e3719d
Create Date: 2025-12-24 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f47ac5282245'
down_revision: Union[str, None] = '6f3f15e3719d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Clean up duplicate user_accounts before adding constraint
    # First, delete dependent documents for the duplicate employees
    op.execute("""
        DELETE FROM studentdocuments
        WHERE employee_id IN (
            SELECT id
            FROM (
                SELECT id,
                ROW_NUMBER() OVER (partition BY user_account ORDER BY id) AS row_num
                FROM employee
            ) t
            WHERE t.row_num > 1
        );
    """)

    # Then delete the duplicate employees
    op.execute("""
        DELETE FROM employee
        WHERE id IN (
            SELECT id
            FROM (
                SELECT id,
                ROW_NUMBER() OVER (partition BY user_account ORDER BY id) AS row_num
                FROM employee
            ) t
            WHERE t.row_num > 1
        );
    """)
    
    # Drop the constraint if it already exists (to handle inconsistent state)
    op.execute("ALTER TABLE employee DROP CONSTRAINT IF EXISTS uq_employee_user_account")
    
    op.create_unique_constraint('uq_employee_user_account', 'employee', ['user_account'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_user_account', 'employee', type_='unique')
    # ### end Alembic commands ###
